[package]
name = "redact-crypto"
version = "0.1.0"
authors = ["Alexandre Pauwels <8890201+ajpauwels@users.noreply.github.com>"]
edition = "2018"
license-file = "LICENSE"
description = "Crypto abstractions for the Redact framework"
documentation = "https://docs.rs/redact-crypto"
repository = "https://github.com/pauwels-labs/redact-crypto.git"
readme = "README.md"
exclude = [
        ".dockerignore",
        ".gitignore",
        ".lighthouse",
        "Dockerfile.test",
        "OWNERS",
        "OWNERS_ALIASES"
]

[dependencies]
async-trait = "0.1.42"
serde = { version = "1.0.125", features = ["derive"] }
sodiumoxide = "0.2.7"
futures = "0.3.8"
mongodb = "1.2.1"
reqwest = { version = "0.11.0", features = ["json"] }
serde_json = "1.0.64"
hex = "0.4.2"
uuid = { version = "0.8.1", features = ["v4", "serde"] }
base64 = "0.13.0"
once_cell = "1.8.0"
ring = { version = "0.16.20", features = ["std"] }
async-recursion = "0.3.2"

[dev-dependencies]
tokio = { version = "1.7.1", features = ["macros", "rt-multi-thread"] }
mockall = "0.9.0"
