[package]
name = "redact-crypto"
version = "0.1.8"
authors = ["Alexandre Pauwels <8890201+ajpauwels@users.noreply.github.com>"]
edition = "2018"
license-file = "LICENSE"
description = "Crypto abstractions for the Redact framework"
documentation = "https://docs.rs/redact-crypto"
repository = "https://github.com/pauwels-labs/redact-crypto.git"
readme = "README.md"
exclude = [
        ".dockerignore",
        ".gitignore",
        ".lighthouse",
        "Dockerfile.test",
        "OWNERS",
        "OWNERS_ALIASES"
]

[dependencies]
async-trait = "0.1.42"
serde = { version = "1.0.125", features = ["derive"] }
sodiumoxide = "0.2.6"
futures = "0.3.8"
mongodb = "1.2.1"
reqwest = { version = "0.11.0", features = ["json"] }
mockall = "0.9.0"
